site_name: Better Than Documentation
theme:
  name: material
  logo: assets/bta.svg
  palette:
    scheme: slate
    primary: blue
    accent: grey
  features:
    - content.code.copy
    - content.tabs
extra_css:
  - assets/custom.css